package hospital;

public class payDues extends javax.swing.JFrame {
    String regno,caseno;
    home q;
    dischargePatient z;
    int i=0;
    int rcharge,acharge,scharge,mcharge,micharge,wcharge,pay,due;
    /** Creates new form payDues */
    public payDues(home h) {
        super("Payment Portal");
        initComponents();
        q=h;
    }

    public payDues(dischargePatient d) {
        initComponents();
        z=d;
        i=1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSucesss = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        labelSucess = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        labelReg = new javax.swing.JLabel();
        labelCase = new javax.swing.JLabel();
        labelAmountPay = new javax.swing.JLabel();
        textCase = new javax.swing.JTextField();
        textAmountPay = new javax.swing.JTextField();
        labelDuePay = new javax.swing.JLabel();
        labelPayDue = new javax.swing.JLabel();
        labelPay = new javax.swing.JLabel();
        buttonPay = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelMedicineCharge = new javax.swing.JLabel();
        labelWardCharge = new javax.swing.JLabel();
        labelMiscCharge = new javax.swing.JLabel();
        labelSurgeryCharge = new javax.swing.JLabel();
        labelRegCharge = new javax.swing.JLabel();
        labelAdmissionCharge = new javax.swing.JLabel();
        textReg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        regCharge = new javax.swing.JLabel();
        admCharge = new javax.swing.JLabel();
        wardCharge = new javax.swing.JLabel();
        surCharge = new javax.swing.JLabel();
        medCharge = new javax.swing.JLabel();
        misCharge = new javax.swing.JLabel();
        labelPaidAmt = new javax.swing.JLabel();
        buttonClear1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        dialogSucesss.setAlwaysOnTop(true);
        dialogSucesss.setBounds(new java.awt.Rectangle(471, 284, 337, 231));

        labelSucess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSucess.setText("Patient Dues Paid Sucessfully");

        buttonOk.setText("OK");
        buttonOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(labelSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(labelSucess)
                .addGap(32, 32, 32)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout dialogSucesssLayout = new javax.swing.GroupLayout(dialogSucesss.getContentPane());
        dialogSucesss.getContentPane().setLayout(dialogSucesssLayout);
        dialogSucesssLayout.setHorizontalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSucesssLayout.setVerticalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(245, 165, 0, 0));

        jPanel2.setLayout(null);

        labelReg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelReg.setText("Registration No.:");
        jPanel2.add(labelReg);
        labelReg.setBounds(40, 70, 100, 14);

        labelCase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCase.setText("Case No.:");
        jPanel2.add(labelCase);
        labelCase.setBounds(40, 110, 70, 14);

        labelAmountPay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelAmountPay.setText("Amount Being Paid:");
        jPanel2.add(labelAmountPay);
        labelAmountPay.setBounds(350, 250, 150, 20);

        textCase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCaseFocusLost(evt);
            }
        });
        jPanel2.add(textCase);
        textCase.setBounds(190, 110, 154, 20);
        jPanel2.add(textAmountPay);
        textAmountPay.setBounds(500, 250, 100, 20);

        labelDuePay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelDuePay.setText("Payment Due:");
        jPanel2.add(labelDuePay);
        labelDuePay.setBounds(370, 180, 110, 19);

        labelPayDue.setText("           ");
        jPanel2.add(labelPayDue);
        labelPayDue.setBounds(500, 180, 100, 20);

        labelPay.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labelPay.setText("Pay Dues");
        jPanel2.add(labelPay);
        labelPay.setBounds(220, 0, 160, 42);

        buttonPay.setText("Pay");
        buttonPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPayMouseClicked(evt);
            }
        });
        jPanel2.add(buttonPay);
        buttonPay.setBounds(360, 370, 80, 30);

        buttonClear.setText("Clear");
        buttonClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear);
        buttonClear.setBounds(50, 370, 90, 30);

        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });
        jPanel2.add(buttonCancel);
        buttonCancel.setBounds(500, 370, 90, 30);

        labelMedicineCharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelMedicineCharge.setText("Medicine Charges");
        jPanel2.add(labelMedicineCharge);
        labelMedicineCharge.setBounds(40, 290, 110, 14);

        labelWardCharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelWardCharge.setText("Ward Charges");
        jPanel2.add(labelWardCharge);
        labelWardCharge.setBounds(50, 220, 90, 14);

        labelMiscCharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelMiscCharge.setText("Miscellaneous Charges");
        jPanel2.add(labelMiscCharge);
        labelMiscCharge.setBounds(40, 320, 140, 14);

        labelSurgeryCharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSurgeryCharge.setText("Surgery Charges");
        jPanel2.add(labelSurgeryCharge);
        labelSurgeryCharge.setBounds(40, 250, 100, 14);

        labelRegCharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelRegCharge.setText("Registration Charges");
        jPanel2.add(labelRegCharge);
        labelRegCharge.setBounds(40, 150, 120, 14);

        labelAdmissionCharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAdmissionCharge.setText("Admission Charges");
        jPanel2.add(labelAdmissionCharge);
        labelAdmissionCharge.setBounds(40, 190, 110, 14);

        textReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRegActionPerformed(evt);
            }
        });
        jPanel2.add(textReg);
        textReg.setBounds(190, 70, 154, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Amount Paid:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(370, 110, 100, 19);

        regCharge.setText("         ");
        jPanel2.add(regCharge);
        regCharge.setBounds(198, 151, 140, 14);

        admCharge.setText("         ");
        jPanel2.add(admCharge);
        admCharge.setBounds(190, 190, 150, 14);

        wardCharge.setText("         ");
        jPanel2.add(wardCharge);
        wardCharge.setBounds(200, 220, 140, 20);

        surCharge.setText("         ");
        jPanel2.add(surCharge);
        surCharge.setBounds(188, 247, 160, 14);

        medCharge.setText("         ");
        jPanel2.add(medCharge);
        medCharge.setBounds(190, 290, 160, 14);

        misCharge.setText("         ");
        jPanel2.add(misCharge);
        misCharge.setBounds(190, 320, 150, 14);

        labelPaidAmt.setText("          ");
        jPanel2.add(labelPaidAmt);
        labelPaidAmt.setBounds(508, 110, 90, 20);

        buttonClear1.setMnemonic('p');
        buttonClear1.setText("print");
        buttonClear1.setToolTipText("Printing a table");
        buttonClear1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClear1MouseClicked(evt);
            }
        });
        buttonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear1);
        buttonClear1.setBounds(200, 370, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pramiti\\Documents\\hopitalproj_images\\xtra\\hospitalBackground.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -30, 620, 491);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        //home h = new home();
        this.setVisible(false);
        if(i==0) {
            q.setVisible(true);
        } else {
            //textCase.setText(null);
            //textReg.setText(null);
            z.setEnabled(true);
            z.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelMouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        textAmountPay.setText(null);
        textCase.setText(null);
        textReg.setText(null);
        regCharge.setText(null);
        admCharge.setText(null);
        wardCharge.setText(null);
        surCharge.setText(null);
        medCharge.setText(null);
        misCharge.setText(null);
        labelPaidAmt.setText(null);
        labelPayDue.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked
        this.setVisible(false);
        dialogSucesss.setVisible(false);
        if(i==0) {
            q.setVisible(true);
        } else {
            z.setEnabled(true);
            z.due=z.due-Integer.parseInt(textAmountPay.getText());
            z.setVisible(true);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_buttonOkMouseClicked

    public void setAll(String r,String c,String rc,String mc,String sc,String ac,String mic,String wc,String ap,String pd) {
        textReg.setText(r);
        textCase.setText(c);
        regCharge.setText(rc);
        medCharge.setText(mc);
        surCharge.setText(sc);
        admCharge.setText(ac);
        misCharge.setText(mic);
        wardCharge.setText(wc);
        labelPaidAmt.setText(ap);
        labelPayDue.setText(pd);
    }

    private void buttonPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPayMouseClicked
        try {
            Database db=new Database();
            db.getConnection();
            db.ps=db.con.prepareStatement("update payment set paidamt=paidamt+? where regno=? and caseno=?");
            db.ps.setInt(1,Integer.parseInt(textAmountPay.getText()));
            db.ps.setString(2,textReg.getText());
            db.ps.setString(3,textCase.getText());
            db.ps.executeUpdate();
            db.closeAll();
        }
        catch(Exception e) {}
        finally {
        dialogSucesss.setVisible(true);
        }
    }//GEN-LAST:event_buttonPayMouseClicked

    private void textRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRegActionPerformed

    private void textCaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCaseFocusLost
        // TODO add your handling code here:
        try {
       // regno=textReg.getText();
       // caseno=textCase.getText();
        Database db=new Database();
        db.getConnection();
        db.ps=db.con.prepareStatement("select rcharge,mcharge,acharge,scharge,micharge,wcharge,paidamt from payment where regno=? and caseno=?");
        db.ps.setString(1, textReg.getText());
        db.ps.setString(2, textCase.getText());
        db.r=db.ps.executeQuery();
        if(db.r.next()) {
        rcharge=db.r.getInt(1);
        mcharge=db.r.getInt(2);
        acharge=db.r.getInt(3);
        scharge=db.r.getInt(4);
        micharge=db.r.getInt(5);
        wcharge=db.r.getInt(6);
        pay=db.r.getInt(7);
        due=(rcharge+mcharge+acharge+micharge+scharge+wcharge)-pay;
        }
        db.closeAll();
        regCharge.setText(""+rcharge);
        medCharge.setText(""+mcharge);
        admCharge.setText(""+acharge);
        surCharge.setText(""+scharge);
        misCharge.setText(""+micharge);
        wardCharge.setText(""+wcharge);
        labelPaidAmt.setText(""+pay);
        labelPayDue.setText(""+due);
        } catch(Exception e){}
    }//GEN-LAST:event_textCaseFocusLost

    private void buttonClear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClear1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClear1MouseClicked

    private void buttonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear1ActionPerformed
        this.setVisible(false);
       // PDF_APPLICATION_TEST ppp = new PDF_APPLICATION_TEST(this);
        // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_buttonClear1ActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOkActionPerformed

    /**
    * @param args the command line arguments
    *//*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payDues().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admCharge;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonClear1;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonPay;
    private javax.swing.JDialog dialogSucesss;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAdmissionCharge;
    private javax.swing.JLabel labelAmountPay;
    private javax.swing.JLabel labelCase;
    private javax.swing.JLabel labelDuePay;
    private javax.swing.JLabel labelMedicineCharge;
    private javax.swing.JLabel labelMiscCharge;
    private javax.swing.JLabel labelPaidAmt;
    private javax.swing.JLabel labelPay;
    private javax.swing.JLabel labelPayDue;
    private javax.swing.JLabel labelReg;
    private javax.swing.JLabel labelRegCharge;
    private javax.swing.JLabel labelSucess;
    private javax.swing.JLabel labelSurgeryCharge;
    private javax.swing.JLabel labelWardCharge;
    private javax.swing.JLabel medCharge;
    private javax.swing.JLabel misCharge;
    private javax.swing.JLabel regCharge;
    private javax.swing.JLabel surCharge;
    private javax.swing.JTextField textAmountPay;
    private javax.swing.JTextField textCase;
    private javax.swing.JTextField textReg;
    private javax.swing.JLabel wardCharge;
    // End of variables declaration//GEN-END:variables

}
