package hospital;

//import java.util.Date;

public class registerPatient extends javax.swing.JFrame {
    String regno;
    String name;
    String gender;
    String bgrp;
    String address;
    String contact;
    java.sql.Date dat;
    String time;
    home q;

    /** Creates new form registerPatient */
    public registerPatient(home h) {
        super("Register Patient");
        initComponents();
        q=h;
        buttonGroup1.add(radioMale);
        buttonGroup1.add(radioFemale);
        java.util.Date pre=new java.util.Date();
        int year=pre.getYear();
        int month=pre.getMonth();
        int date1=pre.getDate();
        int hours=pre.getHours();
        int mins=pre.getMinutes();
        int sec=pre.getSeconds();
        time=""+hours+":"+mins+":"+sec;
        dat=new java.sql.Date(year,month,date1);
        textdate.setText(""+date1+"-"+(month+1)+"-"+(year+1900));
        textTime.setText(time);
        try {
        Database d=new Database();
        d.getConnection();
        String sql="select regno from patient";
        d.r=d.stmt.executeQuery(sql);
        int i=0;
        while(d.r.next()) {
            i=i+1;
        }
        i=i+1;
        regno=""+i;
        d.closeAll();
        } catch(Exception e) {}
        finally {
            jLabel2.setText(regno);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSucesss = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        labelSucess = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelBlood = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        comboBlood = new javax.swing.JComboBox();
        textdate = new javax.swing.JLabel();
        textTime = new javax.swing.JLabel();
        buttonClear = new javax.swing.JButton();
        buttonSubmit = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelReg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelContact1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAddress = new javax.swing.JTextArea();
        textContact1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        dialogSucesss.setAlwaysOnTop(true);
        dialogSucesss.setBounds(new java.awt.Rectangle(471, 284, 337, 231));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        labelSucess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSucess.setText("Patient Registered Sucessfully");

        buttonOk.setText("OK");
        buttonOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(labelSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout dialogSucesssLayout = new javax.swing.GroupLayout(dialogSucesss.getContentPane());
        dialogSucesss.getContentPane().setLayout(dialogSucesssLayout);
        dialogSucesssLayout.setHorizontalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSucesssLayout.setVerticalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(245, 165, 0, 0));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Registration");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 190, 40);

        labelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelName.setText("Name");
        jPanel1.add(labelName);
        labelName.setBounds(40, 230, 40, 14);

        labelGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelGender.setText("Gender");
        jPanel1.add(labelGender);
        labelGender.setBounds(40, 260, 50, 20);

        labelBlood.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelBlood.setText("Blood Group");
        jPanel1.add(labelBlood);
        labelBlood.setBounds(40, 300, 68, 14);

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDate.setText("Registration Date");
        jPanel1.add(labelDate);
        labelDate.setBounds(40, 520, 110, 14);

        labelTime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTime.setText("Registration Time");
        jPanel1.add(labelTime);
        labelTime.setBounds(40, 570, 140, 10);

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });
        jPanel1.add(textName);
        textName.setBounds(160, 230, 166, 20);

        radioMale.setText("Male");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        jPanel1.add(radioMale);
        radioMale.setBounds(160, 260, 70, 23);

        radioFemale.setText("Female");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(radioFemale);
        radioFemale.setBounds(260, 260, 80, 23);

        comboBlood.setBackground(new java.awt.Color(240, 240, 240));
        comboBlood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        comboBlood.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBloodItemStateChanged(evt);
            }
        });
        comboBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBloodActionPerformed(evt);
            }
        });
        jPanel1.add(comboBlood);
        comboBlood.setBounds(160, 300, 110, 20);

        textdate.setText("jLabel7");
        jPanel1.add(textdate);
        textdate.setBounds(210, 520, 130, 10);

        textTime.setText("jLabel8");
        jPanel1.add(textTime);
        textTime.setBounds(210, 570, 130, 14);

        buttonClear.setText("Clear");
        buttonClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });
        jPanel1.add(buttonClear);
        buttonClear.setBounds(150, 610, 80, 30);

        buttonSubmit.setText("Submit");
        buttonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubmitMouseClicked(evt);
            }
        });
        jPanel1.add(buttonSubmit);
        buttonSubmit.setBounds(250, 610, 90, 30);

        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel);
        buttonCancel.setBounds(350, 609, 80, 30);

        labelReg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelReg.setText("Reg. No");
        jPanel1.add(labelReg);
        labelReg.setBounds(350, 230, 50, 14);

        jLabel2.setText("          ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(417, 225, 80, 20);

        labelAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAddress.setText("Address");
        jPanel1.add(labelAddress);
        labelAddress.setBounds(40, 350, 50, 14);

        labelContact1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelContact1.setText("Contact No.");
        jPanel1.add(labelContact1);
        labelContact1.setBounds(38, 464, 80, 20);

        textAddress.setColumns(20);
        textAddress.setRows(5);
        jScrollPane1.setViewportView(textAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 350, 270, 80);
        jPanel1.add(textContact1);
        textContact1.setBounds(160, 460, 166, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\pramiti\\Documents\\hopitalproj_images\\regimg2.jpg")); // NOI18N
        jLabel3.setText("      ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 215);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBloodActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboBloodActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        //home h = new home();
        this.setVisible(false);
        q.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelMouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        textAddress.setText("");
        textContact1.setText("");
        textName.setText("");
        comboBlood.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked
        //home h = new home();
        this.setVisible(false);
        dialogSucesss.setVisible(false);
        q.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOkMouseClicked

    private void buttonSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubmitMouseClicked
        name=textName.getText();
        address=textAddress.getText();
        contact=(textContact1.getText());
        try {
        Database d=new Database();
        d.getConnection();
        d.ps=d.con.prepareStatement("insert into patient values(?,?,?,?,?,?,?,?)");
        d.ps.setString(1,regno);
        d.ps.setString(2,name);
        d.ps.setString(3,gender);
        d.ps.setString(4,bgrp);
        d.ps.setString(5,address);
        d.ps.setString(6,contact); 
        d.ps.setDate(7,dat);
        d.ps.setString(8, time);
        d.ps.executeUpdate();
        d.closeAll();
        } catch(Exception e) {}
        finally {
        dialogSucesss.setVisible(true);
        }
        
        // TODO add your handling code here
    }//GEN-LAST:event_buttonSubmitMouseClicked

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        // TODO add your handling code here:
        gender=evt.getActionCommand();
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
        // TODO add your handling code here:
        gender=evt.getActionCommand();
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void comboBloodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBloodItemStateChanged
        // TODO add your handling code here:
        bgrp=(String)evt.getItem();
    }//GEN-LAST:event_comboBloodItemStateChanged

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerPatient().setVisible(true);
            }
        });
    }
*/
    //private javax.swing.ButtonGroup bg;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox comboBlood;
    private javax.swing.JDialog dialogSucesss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBlood;
    private javax.swing.JLabel labelContact1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelReg;
    private javax.swing.JLabel labelSucess;
    private javax.swing.JLabel labelTime;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextArea textAddress;
    private javax.swing.JTextField textContact1;
    private javax.swing.JTextField textName;
    private javax.swing.JLabel textTime;
    private javax.swing.JLabel textdate;
    // End of variables declaration//GEN-END:variables

}
