
package hospital;

//import java.sql.*;
public class updateDues extends javax.swing.JFrame {

    home q;
    String charges;
    /** Creates new form updateDues */
    public updateDues(home h) {
        super("Update Dues");
        initComponents();
        q=h;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSucesss = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        labelSucess = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelReg = new javax.swing.JLabel();
        labelCase = new javax.swing.JLabel();
        comboCharge = new javax.swing.JComboBox();
        buttonUpdate = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        textCase = new javax.swing.JTextField();
        textAmt = new javax.swing.JTextField();
        labelUpdate = new javax.swing.JLabel();
        textReg = new javax.swing.JTextField();
        labelCharge = new javax.swing.JLabel();
        labelAmt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        dialogSucesss.setAlwaysOnTop(true);
        dialogSucesss.setBounds(new java.awt.Rectangle(471, 284, 337, 231));

        labelSucess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSucess.setText("Patient Dues Updated Sucessfully");

        buttonOk.setText("OK");
        buttonOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelSucess))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(labelSucess)
                .addGap(35, 35, 35)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout dialogSucesssLayout = new javax.swing.GroupLayout(dialogSucesss.getContentPane());
        dialogSucesss.getContentPane().setLayout(dialogSucesssLayout);
        dialogSucesssLayout.setHorizontalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogSucesssLayout.setVerticalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(250, 145, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        labelReg.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelReg.setText("Registration No.");
        jPanel2.add(labelReg);
        labelReg.setBounds(100, 70, 130, 20);

        labelCase.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelCase.setText("Case No.");
        jPanel2.add(labelCase);
        labelCase.setBounds(110, 120, 80, 19);

        comboCharge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Medicine Charges", "Surgery Charges", "Miscellaneous Charges" }));
        comboCharge.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboChargeItemStateChanged(evt);
            }
        });
        comboCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboChargeActionPerformed(evt);
            }
        });
        jPanel2.add(comboCharge);
        comboCharge.setBounds(280, 180, 170, 20);

        buttonUpdate.setText("Update");
        buttonUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonUpdateMouseClicked(evt);
            }
        });
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(buttonUpdate);
        buttonUpdate.setBounds(260, 310, 70, 30);

        buttonClear.setText("Clear");
        buttonClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });
        jPanel2.add(buttonClear);
        buttonClear.setBounds(120, 310, 70, 30);

        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });
        jPanel2.add(buttonCancel);
        buttonCancel.setBounds(400, 310, 80, 30);

        textCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCaseActionPerformed(evt);
            }
        });
        jPanel2.add(textCase);
        textCase.setBounds(280, 120, 170, 20);
        jPanel2.add(textAmt);
        textAmt.setBounds(280, 240, 170, 20);

        labelUpdate.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labelUpdate.setText("Update dues");
        jPanel2.add(labelUpdate);
        labelUpdate.setBounds(215, 4, 190, 40);
        jPanel2.add(textReg);
        textReg.setBounds(280, 70, 170, 20);

        labelCharge.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelCharge.setText("Charges:");
        jPanel2.add(labelCharge);
        labelCharge.setBounds(110, 170, 90, 30);

        labelAmt.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelAmt.setText("Amount (Rs.):");
        jPanel2.add(labelAmt);
        labelAmt.setBounds(110, 240, 103, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pramiti\\Documents\\hopitalproj_images\\xtra\\hospitalBackground.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-20, 0, 620, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboChargeActionPerformed

    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked
        //home h = new home();
        this.setVisible(false);
        dialogSucesss.setVisible(false);
        q.setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_buttonOkMouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        textCase.setText(null);
        textAmt.setText(null);
        textReg.setText(null);
        comboCharge.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        //home h = new home();
        this.setVisible(false);
        q.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelMouseClicked

    private void buttonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUpdateMouseClicked
        try{
            Database db=new Database();
            db.getConnection();
            if(charges.equalsIgnoreCase("Medicine Charges")){
                db.ps=db.con.prepareStatement("update payment set mcharge=mcharge+? where regno=? and caseno=?");
            }else if(charges.equalsIgnoreCase("Surgery Charges")){
                db.ps=db.con.prepareStatement("update payment set scharge=scharge+? where regno=? and caseno=?");
            }else if(charges.equalsIgnoreCase("Miscellaneous Charges")){
                db.ps=db.con.prepareStatement("update payment set micharge=micharge+? where regno=? and caseno=?");
            }
            db.ps.setInt(1,Integer.parseInt(textAmt.getText()));
            db.ps.setString(2,textReg.getText());
            db.ps.setString(3,textCase.getText());
            db.ps.executeUpdate();
            db.closeAll();
        } catch(Exception e){
        }
        finally{
            dialogSucesss.setVisible(true);
        }
    }//GEN-LAST:event_buttonUpdateMouseClicked

    private void comboChargeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboChargeItemStateChanged
        charges = (String)evt.getItem();
        // TODO add your handling code here:
    }//GEN-LAST:event_comboChargeItemStateChanged

    private void textCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCaseActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUpdateActionPerformed

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateDues().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox comboCharge;
    private javax.swing.JDialog dialogSucesss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAmt;
    private javax.swing.JLabel labelCase;
    private javax.swing.JLabel labelCharge;
    private javax.swing.JLabel labelReg;
    private javax.swing.JLabel labelSucess;
    private javax.swing.JLabel labelUpdate;
    private javax.swing.JTextField textAmt;
    private javax.swing.JTextField textCase;
    private javax.swing.JTextField textReg;
    // End of variables declaration//GEN-END:variables

}
